# Generated by Django 6.0.4 on 2026-04-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dropoff_location',
            field=models.CharField(blank=True, help_text='Default drop-off location for equipment returns', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pickup_location',
            field=models.CharField(blank=True, help_text='Default pickup location for equipment rentals', max_length=255, null=True),
        ),
    ]
