# Generated by Django 6.0.3 on 2026-03-27 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('internal_id', models.CharField(blank=True, help_text='Labs specific ID', max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented'), ('SOLD', 'Sold'), ('MAINTENANCE', 'Maintenance'), ('CALIBRATION', 'Calibration'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=20)),
                ('last_calibration_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_due', models.DateField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='catalog.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('technician_notes', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('equipment_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_history', to='inventory.equipmentunit')),
            ],
        ),
    ]
