# Generated by Django 6.0.3 on 2026-03-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MAINTENANCE', 'Maintenance Reminder'), ('CALIBRATION', 'Calibration Reminder'), ('BOOKING_REMINDER', 'Booking Reminder'), ('OVERDUE_ALERT', 'Overdue Alert')], max_length=20)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
