# Generated by Django 5.2.15 on 2026-06-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='equipment_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.equipmentunit'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Info'), ('SYSTEM', 'System'), ('ROLE_CHANGE', 'Role Change'), ('PAYMENT', 'Payment'), ('MAINTENANCE', 'Maintenance Reminder'), ('CALIBRATION', 'Calibration Reminder'), ('BOOKING_REMINDER', 'Booking Reminder'), ('OVERDUE_ALERT', 'Overdue Alert')], default='INFO', max_length=30),
        ),
    ]
