# Generated by Django 6.0.3 on 2026-03-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('RENTAL', 'Rental'), ('PURCHASE', 'Purchase')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('ACTIVE', 'Active/In use'), ('COMPLETED', 'Completed/Returned'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pick_up_location', models.CharField(blank=True, max_length=255, null=True)),
                ('drop_off_location', models.CharField(blank=True, max_length=255, null=True)),
                ('pick_up_date', models.DateTimeField(blank=True, null=True)),
                ('drop_off_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
